version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
    labels:
      - "dependencies"
    commit-message:
      prefix: "feat(gomod)"
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: monthly
    labels:
      - "dependencies"
    commit-message:
      prefix: "build(docker)"