name: linters

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: GolangCI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
          cache: false
      - uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54
  spicedb:
    name: SpiceDB schema linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: authzed/action-spicedb-validate@v1
        with:
          validationfile: "deployments/schema.yaml"
